---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: my-php-site
spec:
  replicas: 4
  strategy:
   type: RollingUpdate
   rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: bojanja/devops-learning-jenkins-deploy-to-docker:latest
        name: my-php-site
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: my-php-site
spec:
  ports:
  - nodePort: 32223
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: NodePort